### ISSUE TITLE
Having any head on with any armor pieces causes a crash

### ISSUE THREAD

**Issue by TipeSor** [Robysaurus/More-Gear_Fabric#2]
having a skull on while having a set of armor which contains any armor from the mod causes a crash
every time you load the world the game crashes
its only related to the armor not the dimension or any other mod

https://github.com/Robysaurus/More-Gear_Fabric/assets/81228929/4af7965a-fbc0-41c8-b7c8-cdb66bbc9674

**Comment by Corwin17** [comment]
I think I've fixed it but it won't get released until I finish updating the mod to 1.20.6 or 1.21 if that comes out before I finish... unfortunately updating the mod is going to take some time since 1.20.5 introduced so many changes at the code level that I have to rewrite so much of the mod. Plus, I'm in school and have finals going on right now so I won't be able to work on it for a bit. Thanks for reporting it though!
