### ISSUE TITLE
Crashing while wearing more gear armor and an elytra

### ISSUE THREAD

**Issue by Alexkil26** [Robysaurus/More-Gear_Fabric#3]
When I equip my elytra with more gear armor I crashed and each time I try to load in my world it would crash again,

**Comment by Corwin17** [comment]
What other mods do you have? I already added a fix for that in all versions which is weird.

**Comment by Corwin17** [comment]
Is your player wearing anything else other than the elytra and armor from my mod like perhaps armor from another mod as well or a mob head?

**Comment by Alexkil26** [comment]
It happens only when I wear leggings and before it would do it whenever I have a piece of armor of more gear but now it does it with every leggings

**Comment by Alexkil26** [comment]
I use these mods : https://pastebin.com/BULy86SJ

**Comment by Corwin17** [comment]
So the way I originally coded the armor to be able to grant special effects when the full set is worn only works if I account for any other wearables. (I changed it so it works with any other wearable but I'm still working on updating to 1.21 so it's not released yet sry). Basically if you wear any piece of my armor with armor from any other mod or some other wearable like a Mob head which I had forgotten to account for, any error will occur during the check for the full set which causes the crash. The weird thing is that this shouldn't happen for elytras because I did explicitly account for elytras unless you are wearing some other mods elytra...

**Comment by Corwin17** [comment]
So basically if you have any other modded items worn (or mob heads) then yeah that'll crash the game sry.

**Comment by Corwin17** [comment]
I'm working on updating the mod to 1.21 but there is a lot to do and I'm also dealing with summer school and college applications so I've not had much time to work on it. Hopefully I can finish in a couple weeks once I've finished summer school and a few other things and have more time to work on it. Sorry for the inconvenience :(

**Comment by Corwin17** [comment]
I'm not sure what would happen if you turned off the mod and reopened the world but maybe try creating a backup of your world and then do that and take off other modded armor sets etc etc for the time being before turning my mod back on. 🤷

**Comment by Alexkil26** [comment]
Dont worry I play on a server so I can clear the elytra and give me the elytra back

**Comment by Corwin17** [comment]
Ok great!
